////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Automated mass matrix diagonalization                                      //
// A. Alloul, K. De Causmaecker, B. Fuks                                      //
//  Main file for the model LRSM //
// File generated by FeynRules 2.3.24                                         //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "headers.hpp"
#include "Parameters.hpp"
#include "tools.hpp"
#include "MassMatrix.hpp"
#include "MassMatrixTwoMix.hpp"
#include "CPar.hpp"
#include "RPar.hpp"

#include "MassMatrixNF.hpp"

int main(int argc, char* argv[])
{
    //remove the log file
    removeLog();

    //debug prints debugging messages and
    //prints the mass matrices in the output too
    MassMatrix::debug = true;
    Parameters::debug = true;
    Par::debug = true;

    //check whether the arguments given by the user are correct
    checkArguments(argc,argv);

    //set the input file
    SLHABlock::inputfile = *(argv+1);

    //initialise the parameters
    MassMatrix::par->init();

    //mass matrix constructor arguments:
    //Symbol, block, IMblock, matrix dimension, Pdg-Ids, particles' names.//
    int pdgIdUVN[] = {22, 23, 32};
    string pdgNameUVN[] = {"A", "Z", "Zp"};
    new MassMatrix("UVN","VNMix","IMVNMix",3,pdgIdUVN,pdgNameUVN);
    int pdgIdUVC[] = {24, 34};
    string pdgNameUVC[] = {"W", "Wp"};
    new MassMatrix("UVC","VCMix","IMVCMix",2,pdgIdUVC,pdgNameUVC);
    int pdgIdUHD[] = {9000055, 9000056};
    string pdgNameUHD[] = {"DH1", "DH2"};
    new MassMatrix("UHD","HDMix","IMHDMix",2,pdgIdUHD,pdgNameUHD);
    int pdgIdUHC[] = {37, 252, 253, 9000037};
    string pdgNameUHC[] = {"GP1", "GP2", "H1", "H2"};
    new MassMatrix("UHC","HCMix","IMHCMix",4,pdgIdUHC,pdgNameUHC);
    int pdgIdUHN[] = {25, 35, 45, 9000025};
    string pdgNameUHN[] = {"h01", "h02", "h03", "h04"};
    new MassMatrix("UHN","HMix","IMHMix",4,pdgIdUHN,pdgNameUHN);
    int pdgIdUAN[] = {36, 46, 250, 251};
    string pdgNameUAN[] = {"G01", "G02", "a01", "a02"};
    new MassMatrix("UAN","AMix","IMAMix",4,pdgIdUAN,pdgNameUAN);
    int pdgIdCKML[] = {1, 3, 5};
    string pdgNameCKML[] = {"dq[1]", "dq[2]", "dq[3]"};
    new MassMatrixTwoMix("CKML","VCKML","IMVCKML","VCKMR","IMVCKMR",3,pdgIdCKML,pdgNameCKML);
    int pdgIdPMNSL[] = {12, 14, 16, 6000012, 6000014, 6000016};
    string pdgNamePMNSL[] = {"vl[1]", "vl[2]", "vl[3]", "Nl[1]", "Nl[2]", "Nl[3]"};
    new MassMatrixTwoMix("PMNSL","PMNSMIX","IMPMNSMIX","PMNSRMIX","IMPMNSRMIX",6,pdgIdPMNSL,pdgNamePMNSL);

    //diagonalizes all the members of the class MassMatrix and prints the results//
    MassMatrix::generateAll(argc-3,argv+3,*(argv+2));
    return 0;
}

