////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// Automated mass matrix diagonalization                                      //
// A. Alloul, K. De Causmaecker, B. Fuks                                      //
// Cpp header file for the parameters of the model LRSM //
// File generated by FeynRules 2.3.24                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef PARAMETERS_HPP 
#define PARAMETERS_HPP 

#include "headers.hpp" 
#include "SLHABlock.hpp" 
#include "Par.hpp"
#include "CPar.hpp" 
#include "RPar.hpp"

///class storing and treating all the parameters of the model
class Parameters 
{ 
    public:
        ///empty constructor
        Parameters(){};
        ///calling this functions will initialise the parameters
        void init();


        //Declaration of the SLHA Blocks
        ///SLHA block FRVEVS
        SLHABlock * SLHABlock178;
        ///SLHA block GAUGE
        SLHABlock * SLHABlock179;
        ///SLHA block HAL
        SLHABlock * SLHABlock180;
        ///SLHA block HLAM
        SLHABlock * SLHABlock181;
        ///SLHA block HRHO
        SLHABlock * SLHABlock182;
        ///SLHA block IMAL
        SLHABlock * SLHABlock183;
        ///SLHA block IMHLAM
        SLHABlock * SLHABlock184;
        ///SLHA block IMRHO
        SLHABlock * SLHABlock185;
        ///SLHA block IMYL1
        SLHABlock * SLHABlock186;
        ///SLHA block IMYL2
        SLHABlock * SLHABlock187;
        ///SLHA block IMYL3
        SLHABlock * SLHABlock188;
        ///SLHA block IMYL4
        SLHABlock * SLHABlock189;
        ///SLHA block IMYQ1
        SLHABlock * SLHABlock190;
        ///SLHA block IMYQ2
        SLHABlock * SLHABlock191;
        ///SLHA block SMINPUTS
        SLHABlock * SLHABlock192;
        ///SLHA block YL1
        SLHABlock * SLHABlock193;
        ///SLHA block YL2
        SLHABlock * SLHABlock194;
        ///SLHA block YL3
        SLHABlock * SLHABlock195;
        ///SLHA block YL4
        SLHABlock * SLHABlock196;
        ///SLHA block YQ1
        SLHABlock * SLHABlock197;
        ///SLHA block YQ2
        SLHABlock * SLHABlock198;

        ///vector storing the blocks that provide the output 
        vector<SLHABlock*> OutBlocks;

        ///flag for debugging
        static bool debug;

        //Declaration of the parameters
  ///SU(2)_R Higgs triplet vacuum expectation value
      RPar * vR;   
  ///SU(2)_L Higgs triplet vacuum expectation value
      RPar * vL;   
  ///Higgs bidoublet vacuum expectation value
      RPar * v1;   
  ///Higgs bidoublet second vacuum expectation value
      RPar * v1p;   
  ///Inverse of the EW coupling constant at the Z pole
      RPar * aEWM1;   
  ///Strong coupling constant at the Z pole.
      RPar * aS;   
  ///SU(2)_R coupling constant at the Z pole
      RPar * gR;   
  ///SU(2)_L coupling constant at the Z pole
      RPar * gL;   
  ///U(1)Y coupling constant at the Z pole
      RPar * gY;   
  ///U(1)_{B-L} coupling constant at the Z pole
      RPar * gBL;   
  ///Strong coupling constant
      RPar * gs;   
  ///Quark Yukawa matrix 1 (real part)
      RPar * Ryq11x1;   
  ///Quark Yukawa matrix 1 (real part)
      RPar * Ryq11x2;   
  ///Quark Yukawa matrix 1 (real part)
      RPar * Ryq11x3;   
  ///Quark Yukawa matrix 1 (real part)
      RPar * Ryq12x1;   
  ///Quark Yukawa matrix 1 (real part)
      RPar * Ryq12x2;   
  ///Quark Yukawa matrix 1 (real part)
      RPar * Ryq12x3;   
  ///Quark Yukawa matrix 1 (real part)
      RPar * Ryq13x1;   
  ///Quark Yukawa matrix 1 (real part)
      RPar * Ryq13x2;   
  ///Quark Yukawa matrix 1 (real part)
      RPar * Ryq13x3;   
  ///Quark Yukawa matrix 1 (imaginary part)
      RPar * Iyq11x1;   
  ///Quark Yukawa matrix 1 (imaginary part)
      RPar * Iyq11x2;   
  ///Quark Yukawa matrix 1 (imaginary part)
      RPar * Iyq11x3;   
  ///Quark Yukawa matrix 1 (imaginary part)
      RPar * Iyq12x1;   
  ///Quark Yukawa matrix 1 (imaginary part)
      RPar * Iyq12x2;   
  ///Quark Yukawa matrix 1 (imaginary part)
      RPar * Iyq12x3;   
  ///Quark Yukawa matrix 1 (imaginary part)
      RPar * Iyq13x1;   
  ///Quark Yukawa matrix 1 (imaginary part)
      RPar * Iyq13x2;   
  ///Quark Yukawa matrix 1 (imaginary part)
      RPar * Iyq13x3;   
  ///Quark Yukawa matrix 2 (real part)
      RPar * Ryq21x1;   
  ///Quark Yukawa matrix 2 (real part)
      RPar * Ryq21x2;   
  ///Quark Yukawa matrix 2 (real part)
      RPar * Ryq21x3;   
  ///Quark Yukawa matrix 2 (real part)
      RPar * Ryq22x1;   
  ///Quark Yukawa matrix 2 (real part)
      RPar * Ryq22x2;   
  ///Quark Yukawa matrix 2 (real part)
      RPar * Ryq22x3;   
  ///Quark Yukawa matrix 2 (real part)
      RPar * Ryq23x1;   
  ///Quark Yukawa matrix 2 (real part)
      RPar * Ryq23x2;   
  ///Quark Yukawa matrix 2 (real part)
      RPar * Ryq23x3;   
  ///Quark Yukawa matrix 2 (imaginary part)
      RPar * Iyq21x1;   
  ///Quark Yukawa matrix 2 (imaginary part)
      RPar * Iyq21x2;   
  ///Quark Yukawa matrix 2 (imaginary part)
      RPar * Iyq21x3;   
  ///Quark Yukawa matrix 2 (imaginary part)
      RPar * Iyq22x1;   
  ///Quark Yukawa matrix 2 (imaginary part)
      RPar * Iyq22x2;   
  ///Quark Yukawa matrix 2 (imaginary part)
      RPar * Iyq22x3;   
  ///Quark Yukawa matrix 2 (imaginary part)
      RPar * Iyq23x1;   
  ///Quark Yukawa matrix 2 (imaginary part)
      RPar * Iyq23x2;   
  ///Quark Yukawa matrix 2 (imaginary part)
      RPar * Iyq23x3;   
  ///Lepton Yukawa matrix 1 (real part)
      RPar * Ryl11x1;   
  ///Lepton Yukawa matrix 1 (real part)
      RPar * Ryl11x2;   
  ///Lepton Yukawa matrix 1 (real part)
      RPar * Ryl11x3;   
  ///Lepton Yukawa matrix 1 (real part)
      RPar * Ryl12x1;   
  ///Lepton Yukawa matrix 1 (real part)
      RPar * Ryl12x2;   
  ///Lepton Yukawa matrix 1 (real part)
      RPar * Ryl12x3;   
  ///Lepton Yukawa matrix 1 (real part)
      RPar * Ryl13x1;   
  ///Lepton Yukawa matrix 1 (real part)
      RPar * Ryl13x2;   
  ///Lepton Yukawa matrix 1 (real part)
      RPar * Ryl13x3;   
  ///Lepton Yukawa matrix 1 (imaginary part)
      RPar * Iyl11x1;   
  ///Lepton Yukawa matrix 1 (imaginary part)
      RPar * Iyl11x2;   
  ///Lepton Yukawa matrix 1 (imaginary part)
      RPar * Iyl11x3;   
  ///Lepton Yukawa matrix 1 (imaginary part)
      RPar * Iyl12x1;   
  ///Lepton Yukawa matrix 1 (imaginary part)
      RPar * Iyl12x2;   
  ///Lepton Yukawa matrix 1 (imaginary part)
      RPar * Iyl12x3;   
  ///Lepton Yukawa matrix 1 (imaginary part)
      RPar * Iyl13x1;   
  ///Lepton Yukawa matrix 1 (imaginary part)
      RPar * Iyl13x2;   
  ///Lepton Yukawa matrix 1 (imaginary part)
      RPar * Iyl13x3;   
  ///Lepton Yukawa matrix 2 (real part)
      RPar * Ryl21x1;   
  ///Lepton Yukawa matrix 2 (real part)
      RPar * Ryl21x2;   
  ///Lepton Yukawa matrix 2 (real part)
      RPar * Ryl21x3;   
  ///Lepton Yukawa matrix 2 (real part)
      RPar * Ryl22x1;   
  ///Lepton Yukawa matrix 2 (real part)
      RPar * Ryl22x2;   
  ///Lepton Yukawa matrix 2 (real part)
      RPar * Ryl22x3;   
  ///Lepton Yukawa matrix 2 (real part)
      RPar * Ryl23x1;   
  ///Lepton Yukawa matrix 2 (real part)
      RPar * Ryl23x2;   
  ///Lepton Yukawa matrix 2 (real part)
      RPar * Ryl23x3;   
  ///Lepton Yukawa matrix 2 (imaginary part)
      RPar * Iyl21x1;   
  ///Lepton Yukawa matrix 2 (imaginary part)
      RPar * Iyl21x2;   
  ///Lepton Yukawa matrix 2 (imaginary part)
      RPar * Iyl21x3;   
  ///Lepton Yukawa matrix 2 (imaginary part)
      RPar * Iyl22x1;   
  ///Lepton Yukawa matrix 2 (imaginary part)
      RPar * Iyl22x2;   
  ///Lepton Yukawa matrix 2 (imaginary part)
      RPar * Iyl22x3;   
  ///Lepton Yukawa matrix 2 (imaginary part)
      RPar * Iyl23x1;   
  ///Lepton Yukawa matrix 2 (imaginary part)
      RPar * Iyl23x2;   
  ///Lepton Yukawa matrix 2 (imaginary part)
      RPar * Iyl23x3;   
  ///Lepton Yukawa matrix 3 (real part)
      RPar * Ryl31x1;   
  ///Lepton Yukawa matrix 3 (real part)
      RPar * Ryl31x2;   
  ///Lepton Yukawa matrix 3 (real part)
      RPar * Ryl31x3;   
  ///Lepton Yukawa matrix 3 (real part)
      RPar * Ryl32x1;   
  ///Lepton Yukawa matrix 3 (real part)
      RPar * Ryl32x2;   
  ///Lepton Yukawa matrix 3 (real part)
      RPar * Ryl32x3;   
  ///Lepton Yukawa matrix 3 (real part)
      RPar * Ryl33x1;   
  ///Lepton Yukawa matrix 3 (real part)
      RPar * Ryl33x2;   
  ///Lepton Yukawa matrix 3 (real part)
      RPar * Ryl33x3;   
  ///Lepton Yukawa matrix 3 (imaginary part)
      RPar * Iyl31x1;   
  ///Lepton Yukawa matrix 3 (imaginary part)
      RPar * Iyl31x2;   
  ///Lepton Yukawa matrix 3 (imaginary part)
      RPar * Iyl31x3;   
  ///Lepton Yukawa matrix 3 (imaginary part)
      RPar * Iyl32x1;   
  ///Lepton Yukawa matrix 3 (imaginary part)
      RPar * Iyl32x2;   
  ///Lepton Yukawa matrix 3 (imaginary part)
      RPar * Iyl32x3;   
  ///Lepton Yukawa matrix 3 (imaginary part)
      RPar * Iyl33x1;   
  ///Lepton Yukawa matrix 3 (imaginary part)
      RPar * Iyl33x2;   
  ///Lepton Yukawa matrix 3 (imaginary part)
      RPar * Iyl33x3;   
  ///Lepton Yukawa matrix 4 (real part)
      RPar * Ryl41x1;   
  ///Lepton Yukawa matrix 4 (real part)
      RPar * Ryl41x2;   
  ///Lepton Yukawa matrix 4 (real part)
      RPar * Ryl41x3;   
  ///Lepton Yukawa matrix 4 (real part)
      RPar * Ryl42x1;   
  ///Lepton Yukawa matrix 4 (real part)
      RPar * Ryl42x2;   
  ///Lepton Yukawa matrix 4 (real part)
      RPar * Ryl42x3;   
  ///Lepton Yukawa matrix 4 (real part)
      RPar * Ryl43x1;   
  ///Lepton Yukawa matrix 4 (real part)
      RPar * Ryl43x2;   
  ///Lepton Yukawa matrix 4 (real part)
      RPar * Ryl43x3;   
  ///Lepton Yukawa matrix 4 (imaginary part)
      RPar * Iyl41x1;   
  ///Lepton Yukawa matrix 4 (imaginary part)
      RPar * Iyl41x2;   
  ///Lepton Yukawa matrix 4 (imaginary part)
      RPar * Iyl41x3;   
  ///Lepton Yukawa matrix 4 (imaginary part)
      RPar * Iyl42x1;   
  ///Lepton Yukawa matrix 4 (imaginary part)
      RPar * Iyl42x2;   
  ///Lepton Yukawa matrix 4 (imaginary part)
      RPar * Iyl42x3;   
  ///Lepton Yukawa matrix 4 (imaginary part)
      RPar * Iyl43x1;   
  ///Lepton Yukawa matrix 4 (imaginary part)
      RPar * Iyl43x2;   
  ///Lepton Yukawa matrix 4 (imaginary part)
      RPar * Iyl43x3;   
  ///1st bidoublet quartic term  (real part)
      RPar * RLAM1;   
  ///1st bidoublet quartic term (imaginary part)
      RPar * ILAM1;   
  ///2nd bidoublet quartic term(real part)
      RPar * RLAM2;   
  ///2nd bidoublet quartic term (imaginary part)
      RPar * ILAM2;   
  ///3rd bidoublet quartic term  (real part)
      RPar * RLAM3;   
  ///3rd bidoublet quartic term  (imaginary part)
      RPar * ILAM3;   
  ///4th bidoublet quartic term  (real part)
      RPar * RLAM4;   
  ///4th bidoublet quartic term  (imaginary part)
      RPar * ILAM4;   
  ///5th bidoublet quartic term  (real part)
      RPar * RLAM5;   
  ///5th bidoublet quartic term  (imaginary part)
      RPar * ILAM5;   
  ///6th bidoublet quartic term  (real part)
      RPar * RLAM6;   
  ///6th bidoublet quartic term  (imaginary part)
      RPar * ILAM6;   
  ///1st triplet quartic term  (real part)
      RPar * RRHO1;   
  ///1st triplet  quartic term  (imaginary part)
      RPar * IRHO1;   
  ///2nd triplet quartic term  (real part)
      RPar * RRHO2;   
  ///2nd triplet  quartic term  (imaginary part)
      RPar * IRHO2;   
  ///3rd triplet quartic term  (real part)
      RPar * RRHO3;   
  ///3rd triplet  quartic term  (imaginary part)
      RPar * IRHO3;   
  ///1st bidoubet-triplets quartic term  (real part)
      RPar * RAL1;   
  ///1st bidoubet-triplets quartic term (imaginary part)
      RPar * IAL1;   
  ///2nd bidoubet-triplets quartic term  (real part)
      RPar * RAL2;   
  ///2nd bidoubet-triplets quartic term (imaginary part)
      RPar * IAL2;   
  ///3rd bidoubet-triplets quartic term  (real part)
      RPar * RAL3;   
  ///3rd bidoubet-triplets quartic term (imaginary part)
      RPar * IAL3;   
 /// Quark Yukawa matrix 1
       CPar * yq11x1;  
 /// Quark Yukawa matrix 1
       CPar * yq11x2;  
 /// Quark Yukawa matrix 1
       CPar * yq11x3;  
 /// Quark Yukawa matrix 1
       CPar * yq12x1;  
 /// Quark Yukawa matrix 1
       CPar * yq12x2;  
 /// Quark Yukawa matrix 1
       CPar * yq12x3;  
 /// Quark Yukawa matrix 1
       CPar * yq13x1;  
 /// Quark Yukawa matrix 1
       CPar * yq13x2;  
 /// Quark Yukawa matrix 1
       CPar * yq13x3;  
 /// Quark Yukawa matrix 2
       CPar * yq21x1;  
 /// Quark Yukawa matrix 2
       CPar * yq21x2;  
 /// Quark Yukawa matrix 2
       CPar * yq21x3;  
 /// Quark Yukawa matrix 2
       CPar * yq22x1;  
 /// Quark Yukawa matrix 2
       CPar * yq22x2;  
 /// Quark Yukawa matrix 2
       CPar * yq22x3;  
 /// Quark Yukawa matrix 2
       CPar * yq23x1;  
 /// Quark Yukawa matrix 2
       CPar * yq23x2;  
 /// Quark Yukawa matrix 2
       CPar * yq23x3;  
 /// Lepton Yukawa matrix 1
       CPar * yl11x1;  
 /// Lepton Yukawa matrix 1
       CPar * yl11x2;  
 /// Lepton Yukawa matrix 1
       CPar * yl11x3;  
 /// Lepton Yukawa matrix 1
       CPar * yl12x1;  
 /// Lepton Yukawa matrix 1
       CPar * yl12x2;  
 /// Lepton Yukawa matrix 1
       CPar * yl12x3;  
 /// Lepton Yukawa matrix 1
       CPar * yl13x1;  
 /// Lepton Yukawa matrix 1
       CPar * yl13x2;  
 /// Lepton Yukawa matrix 1
       CPar * yl13x3;  
 /// Lepton Yukawa matrix 2
       CPar * yl21x1;  
 /// Lepton Yukawa matrix 2
       CPar * yl21x2;  
 /// Lepton Yukawa matrix 2
       CPar * yl21x3;  
 /// Lepton Yukawa matrix 2
       CPar * yl22x1;  
 /// Lepton Yukawa matrix 2
       CPar * yl22x2;  
 /// Lepton Yukawa matrix 2
       CPar * yl22x3;  
 /// Lepton Yukawa matrix 2
       CPar * yl23x1;  
 /// Lepton Yukawa matrix 2
       CPar * yl23x2;  
 /// Lepton Yukawa matrix 2
       CPar * yl23x3;  
 /// Lepton Yukawa matrix 3
       CPar * yl31x1;  
 /// Lepton Yukawa matrix 3
       CPar * yl31x2;  
 /// Lepton Yukawa matrix 3
       CPar * yl31x3;  
 /// Lepton Yukawa matrix 3
       CPar * yl32x1;  
 /// Lepton Yukawa matrix 3
       CPar * yl32x2;  
 /// Lepton Yukawa matrix 3
       CPar * yl32x3;  
 /// Lepton Yukawa matrix 3
       CPar * yl33x1;  
 /// Lepton Yukawa matrix 3
       CPar * yl33x2;  
 /// Lepton Yukawa matrix 3
       CPar * yl33x3;  
 /// Lepton Yukawa matrix 4
       CPar * yl41x1;  
 /// Lepton Yukawa matrix 4
       CPar * yl41x2;  
 /// Lepton Yukawa matrix 4
       CPar * yl41x3;  
 /// Lepton Yukawa matrix 4
       CPar * yl42x1;  
 /// Lepton Yukawa matrix 4
       CPar * yl42x2;  
 /// Lepton Yukawa matrix 4
       CPar * yl42x3;  
 /// Lepton Yukawa matrix 4
       CPar * yl43x1;  
 /// Lepton Yukawa matrix 4
       CPar * yl43x2;  
 /// Lepton Yukawa matrix 4
       CPar * yl43x3;  
 /// 1st bidoublet quartic term
       CPar * lam1;  
 /// 2md bidoublet quartic term
       CPar * lam2;  
 /// 3rd bidoublet quartic term
       CPar * lam3;  
 /// 4th bidoublet quartic term
       CPar * lam4;  
 /// 5th bidoublet quartic term
       CPar * lam5;  
 /// 6th bidoublet quartic term
       CPar * lam6;  
 ///  1st triplets quartic term
       CPar * rho1;  
 ///  2nd triplets quartic term
       CPar * rho2;  
 ///  3rd triplets quartic term
       CPar * rho3;  
 ///  1st bidoubet-triplets quartic term
       CPar * al1;  
 ///  2nd bidoubet-triplets quartic term
       CPar * al2;  
 ///  3rd bidoubet-triplets quartic term
       CPar * al3;  
 /// Square of the bidoublet quadratic term
       CPar * mu12;  
 /// Bidoublet quadratic term
       CPar * mu1;  
 /// Square of the triplet quadratic term
       CPar * mu22;  
 /// Triplet quadratic term
       CPar * mu2;  

    ///map to store the pointers to the functions initialising the mass matrices 
    map <string,initFP> massInit;
    map <string,initFP2> massInit2;
    ///function to initialise the UVN mass matrix
    void initUVN(gsl_matrix_complex *);
    ///function to initialise the UVC mass matrix
    void initUVC(gsl_matrix_complex *);
    ///function to initialise the UHD mass matrix
    void initUHD(gsl_matrix_complex *);
    ///function to initialise the UHC mass matrix
    void initUHC(gsl_matrix_complex *);
    ///function to initialise the UHN mass matrix
    void initUHN(gsl_matrix_complex *);
    ///function to initialise the UAN mass matrix
    void initUAN(gsl_matrix_complex *);
    ///function to initialise the CKML mass matrix
    void initCKML(gsl_matrix_complex *,gsl_matrix_complex *);
    ///function to initialise the PMNSL mass matrix
    void initPMNSL(gsl_matrix_complex *,gsl_matrix_complex *);
    ///prints the parameters belonging to a block
    void printParameters(ofstream &); 
};
#endif